"""The declared fields of each record type when the declarations first shipped.

A stored database and the segment files depend on these names, types, and units, so the
declarations may only grow. Append a new field at the end of its class. Never rename,
remove, or retype a field, and never make an optional field required. Each tuple holds
the name, the type, whether the type includes `None`, and the unit. The base fields
(`station_id` to `quality`) are not listed here, because `test_baseline.py` lists them once.

To record a field that you add, append its tuple here. That step is optional.
"""

from __future__ import annotations

BASELINE: dict[str, tuple[tuple[str, str, bool, str | None], ...]] = {
    "frame": (
        ("stream_id", "int", False, None),
        ("seq", "int", False, None),
        ("t_err_us", "int", False, "us"),
        ("cx_px", "float", True, "px"),
        ("cy_px", "float", True, "px"),
        ("width_x_px", "float", True, "px"),
        ("width_y_px", "float", True, "px"),
        ("peak_dn", "int", False, "DN"),
        ("flux_e", "float", True, "e-"),
        ("bg_dn", "float", True, "DN"),
        ("flags", "int", False, None),
        ("dropped_before", "int", False, None),
    ),
    "seeing_window": (
        ("duration_s", "float", False, "s"),
        ("stream_id", "int", False, None),
        ("readout_mode", "str", False, None),
        ("exposure_us", "int", False, "us"),
        ("gain", "int", False, None),
        ("n_frames", "int", False, None),
        ("n_dropped", "int", False, None),
        ("valid_fraction", "float", False, None),
        ("frame_rate_hz", "float", True, "Hz"),
        ("image_motion_rms_x_arcsec", "float", True, "arcsec"),
        ("image_motion_rms_y_arcsec", "float", True, "arcsec"),
        ("seeing_fwhm_arcsec", "float", True, "arcsec"),
        ("r0_cm", "float", True, "cm"),
        ("seeing_fwhm_structure_arcsec", "float", True, "arcsec"),
        ("r0_structure_cm", "float", True, "cm"),
        ("scintillation_index", "float", True, None),
        ("centroid_noise_px", "float", True, "px"),
        ("width_fwhm_arcsec", "float", True, "arcsec"),
        ("peak_mean_dn", "float", True, "DN"),
        ("flux_mean_e", "float", True, "e-"),
        ("background_mean_dn", "float", True, "DN"),
        ("saturated_fraction", "float", True, None),
        ("outer_scale_m", "float", True, "m"),
        ("assumed_wind_ms", "float", True, "m/s"),
        ("exposure_correction_factor", "float", True, None),
        ("outer_scale_correction_factor", "float", True, None),
        ("zenith_angle_deg", "float", True, "deg"),
        ("motion_psd_freq_hz", "list[float]", True, "Hz"),
        ("motion_psd_x_arcsec2_per_hz", "list[float]", True, "arcsec^2/Hz"),
        ("motion_psd_y_arcsec2_per_hz", "list[float]", True, "arcsec^2/Hz"),
        ("vibration_lines_hz", "list[float]", True, "Hz"),
        ("heater_duty", "float", True, None),
        ("sensor_temperature_c", "float", True, "degC"),
        ("flags", "list[str]", False, None),
    ),
    "survey_frame": (
        ("exposure_s", "float", False, "s"),
        ("gain", "int", False, None),
        ("readout_mode", "str", False, None),
        ("sensor_temperature_c", "float", True, "degC"),
        ("image_ref", "str", True, None),
        ("n_detected", "int", True, None),
        ("n_saturated", "int", True, None),
        ("background_dn", "float", True, "DN"),
    ),
    "sky_quality": (
        ("sky_mag_arcsec2", "float", True, "mag/arcsec^2"),
        ("sky_mag_arcsec2_v", "float", True, "mag/arcsec^2"),
        ("zero_point_mag", "float", True, "mag"),
        ("zero_point_rms_mag", "float", True, "mag"),
        ("color_term", "float", True, None),
        ("transparency", "float", True, None),
        ("cloud_fraction", "float", True, None),
        ("limiting_mag", "float", True, "mag"),
        ("n_stars_used", "int", False, None),
        ("sky_rate_e_per_s_arcsec2", "float", True, "e-/s/arcsec^2"),
        ("dark_model_version", "str", True, None),
        ("flags", "list[str]", False, None),
    ),
    "pointing": (
        ("center_ra_deg", "float", True, "deg"),
        ("center_dec_deg", "float", True, "deg"),
        ("roll_deg", "float", True, "deg"),
        ("plate_scale_arcsec_px", "float", True, "arcsec/px"),
        ("attitude", "list[float]", True, None),
        ("offset_arcmin", "float", True, "arcmin"),
        ("solve_rms_arcsec", "float", True, "arcsec"),
        ("n_matched", "int", False, None),
        ("focus_fwhm_px", "float", True, "px"),
        ("polaris_x_px", "float", True, "px"),
        ("polaris_y_px", "float", True, "px"),
        ("readout_mode", "str", False, None),
        ("solver", "str", False, None),
        ("solve_time_s", "float", True, "s"),
        ("reference_id", "str", True, None),
        ("flags", "list[str]", False, None),
    ),
    "star_list": (
        ("n_stars", "int", False, None),
        ("columns", "list[str]", False, None),
        ("data", "bytes", False, None),
        ("catalog", "str", True, None),
    ),
    "star_epoch": (
        ("night", "str", False, None),
        ("n_stars", "int", False, None),
        ("n_frames", "int", False, None),
        ("columns", "list[str]", False, None),
        ("data", "bytes", False, None),
    ),
    "reference": (
        ("instrument", "str", False, None),
        ("source", "str", False, None),
        ("value_mag_arcsec2", "float", False, "mag/arcsec^2"),
        ("temperature_c", "float", True, "degC"),
        ("altitude_deg", "float", True, "deg"),
        ("azimuth_deg", "float", True, "deg"),
        ("note", "str", True, None),
    ),
    "health": (
        ("state", "str", False, None),
        ("degraded", "bool", False, None),
        ("components", "dict[str, str]", False, None),
        ("sensor_temperature_c", "float", True, "degC"),
        ("heater_duty", "float", True, None),
        ("free_space_gb", "float", True, "GB"),
        ("data_used_gb", "float", True, "GB"),
        ("dropped_total", "int", True, None),
        ("queue_depth", "int", True, None),
        ("sink_backlog", "dict[str, int]", False, None),
        ("time_synchronized", "bool", True, None),
        ("time_error_bound_ms", "float", True, "ms"),
        ("uptime_s", "float", True, "s"),
        ("cpu_load_1m", "float", True, None),
        ("memory_used_mb", "float", True, "MB"),
        ("dark_due", "bool", False, None),
        ("flags", "list[str]", False, None),
    ),
    "event": (
        ("level", "str", False, None),
        ("kind", "str", False, None),
        ("message", "str", False, None),
        ("detail", "dict[str, Any]", True, None),
    ),
    "run": (
        ("run_id", "str", False, None),
        ("software_version", "str", False, None),
        ("versions", "dict[str, str]", False, None),
        ("effective_config", "dict[str, Any]", False, None),
        ("profile", "dict[str, Any]", False, None),
    ),
}
