from __future__ import annotations

import contextlib
import sqlite3
from collections.abc import Iterator
from typing import Any

import pytest
from hypothesis import given
from hypothesis import strategies as st

from seeingmon.records.base import Record, field_specs, quantity
from seeingmon.records.seeing import SeeingWindowRecord
from seeingmon.records.sqlite_schema import (
    SchemaError,
    create_index_sql,
    create_table_sql,
    ensure_schema,
    insert_sql,
    migration_statements,
    row_to_sqlite,
    schema_sql,
    schema_statements,
    select_after_sql,
    sqlite_to_row,
    table_record_types,
    upsert_sql,
)
from seeingmon.records.system import EventRecord, HealthRecord
from tests.records.strategies import (
    ALL_RECORD_TYPES,
    minimal_values,
    record_values,
    records,
    type_id,
)

TABLE_TYPES = [cls for cls in ALL_RECORD_TYPES if cls.storage == "table"]
SQL_TYPES = {
    "int": "INTEGER",
    "float": "REAL",
    "bool": "INTEGER",
    "str": "TEXT",
    "bytes": "BLOB",
    "json": "TEXT",
}


@contextlib.contextmanager
def memory_db() -> Iterator[sqlite3.Connection]:
    connection = sqlite3.connect(":memory:")
    connection.row_factory = sqlite3.Row
    try:
        yield connection
    finally:
        connection.close()


def table_names(db: sqlite3.Connection) -> set[str]:
    rows = db.execute("SELECT name FROM sqlite_master WHERE type = 'table'").fetchall()
    return {row["name"] for row in rows if not row["name"].startswith("sqlite_")}


def table_info(db: sqlite3.Connection, table: str) -> list[sqlite3.Row]:
    return db.execute(f'PRAGMA table_info("{table}")').fetchall()


def insert(db: sqlite3.Connection, record: Record) -> int:
    cursor = db.execute(insert_sql(type(record)), row_to_sqlite(type(record), record.to_row()))
    assert cursor.lastrowid is not None
    return cursor.lastrowid


def event(**overrides: Any) -> EventRecord:
    values: dict[str, Any] = {
        "station_id": "station-a",
        "t_utc_ns": 1_800_000_000_000_000_000,
        "profile_id": "profile-a",
        "provenance": {"software": "0.1.0"},
        "level": "info",
        "kind": "scheduler.state_change",
        "message": "The scheduler entered the auto state.",
    }
    values.update(overrides)
    return EventRecord(**values)


EVENT_DDL = """\
CREATE TABLE IF NOT EXISTS "event" (
    "row_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "station_id" TEXT NOT NULL,
    "t_utc_ns" INTEGER NOT NULL,
    "revision" INTEGER NOT NULL DEFAULT 0,
    "profile_id" TEXT NOT NULL,
    "provenance" TEXT NOT NULL CHECK (json_valid("provenance")),
    "quality" TEXT CHECK (json_valid("quality")),
    "level" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "detail" TEXT CHECK (json_valid("detail")),
    UNIQUE ("station_id", "t_utc_ns", "revision")
)"""


class TestSchema:
    def test_every_table_record_type_gets_a_table_and_a_segment_type_gets_none(self) -> None:
        assert {cls.record_type for cls in table_record_types()} == {
            cls.record_type for cls in TABLE_TYPES
        }
        with memory_db() as db:
            changes = ensure_schema(db)
            assert table_names(db) == {cls.record_type for cls in TABLE_TYPES}
        assert "frame" not in table_names_of(changes)
        assert len(TABLE_TYPES) == 10

    def test_the_schema_script_runs_on_an_empty_database(self) -> None:
        script = schema_sql()
        assert script.startswith("-- Generated by")
        with memory_db() as db:
            db.executescript(script)
            assert table_names(db) == {cls.record_type for cls in TABLE_TYPES}
            assert ensure_schema(db) == []  # the script already created everything

    def test_the_statements_match_the_script(self) -> None:
        statements = schema_statements()
        assert sum(s.startswith("CREATE TABLE") for s in statements) == len(TABLE_TYPES)
        assert sum(s.startswith("CREATE INDEX") for s in statements) == len(TABLE_TYPES)
        assert all(f"{s};" in schema_sql() for s in statements)

    def test_a_segment_record_has_no_table(self) -> None:
        for function in (create_table_sql, create_index_sql, insert_sql, upsert_sql):
            with pytest.raises(ValueError, match="no SQLite table"):
                function("frame")
        with pytest.raises(ValueError, match="no SQLite table"):
            schema_statements(["frame"])

    def test_the_event_table_is_as_documented(self) -> None:
        assert create_table_sql("event") == EVENT_DDL
        assert create_index_sql("event") == [
            'CREATE INDEX IF NOT EXISTS "ix_event_t_utc_ns" ON "event" ("t_utc_ns")'
        ]

    @pytest.mark.parametrize("cls", TABLE_TYPES, ids=type_id)
    def test_columns_follow_the_declaration(self, cls: type[Record]) -> None:
        specs = field_specs(cls)
        with memory_db() as db:
            db.execute(create_table_sql(cls))
            info = table_info(db, cls.record_type)
        assert [row["name"] for row in info] == ["row_id", *(spec.name for spec in specs)]
        assert (info[0]["type"], info[0]["pk"], info[0]["notnull"]) == ("INTEGER", 1, 0)
        for row, spec in zip(info[1:], specs, strict=True):
            assert row["type"] == SQL_TYPES[spec.kind], spec.name
            assert bool(row["notnull"]) == (not spec.nullable), spec.name
        assert [spec.name for spec in specs[:3]] == ["station_id", "t_utc_ns", "revision"]

    def test_a_default_in_the_declaration_is_a_default_in_the_column(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(HealthRecord))
            columns = {row["name"]: row["dflt_value"] for row in table_info(db, "health")}
        assert columns["revision"] == "0"
        assert columns["flags"] == "'[]'"
        assert columns["sink_backlog"] == "'{}'"
        assert columns["state"] is None
        assert columns["heater_duty"] is None


def table_names_of(statements: list[str]) -> set[str]:
    return {s.split('"')[1] for s in statements if s.startswith("CREATE TABLE")}


class TestRows:
    @pytest.mark.parametrize("cls", TABLE_TYPES, ids=type_id)
    @given(data=st.data())
    def test_a_record_survives_a_trip_through_sqlite(
        self, cls: type[Record], data: st.DataObject
    ) -> None:
        record = data.draw(records(cls))
        with memory_db() as db:
            db.execute(create_table_sql(cls))
            row_id = insert(db, record)
            stored = db.execute(f'SELECT * FROM "{cls.record_type}"').fetchall()
        assert len(stored) == 1
        assert stored[0]["row_id"] == row_id
        assert cls.from_row(sqlite_to_row(cls, stored[0]), strict=True) == record

    def test_sqlite_to_row_accepts_a_dict_and_leaves_out_what_the_table_lacks(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(EventRecord))
            insert(db, event(detail={"a": [1, 2]}))
            stored = dict(db.execute('SELECT * FROM "event"').fetchone())
        row = sqlite_to_row(EventRecord, stored)
        assert "row_id" not in row
        assert row["detail"] == {"a": [1, 2]}
        assert sqlite_to_row("event", {"level": "info"}) == {"level": "info"}

    def test_row_to_sqlite_encodes_booleans_json_and_bytes(self) -> None:
        window = SeeingWindowRecord(**minimal_values("seeing_window"), flags=["cloud"])
        params = row_to_sqlite(SeeingWindowRecord, window.to_row())
        assert params["flags"] == '["cloud"]'
        assert params["provenance"] == "{}"
        assert params["quality"] is None
        health = HealthRecord(**minimal_values("health"), time_synchronized=True)
        assert row_to_sqlite("health", health.to_row())["time_synchronized"] == 1
        assert row_to_sqlite("health", health.to_row())["degraded"] == 0

    def test_a_missing_field_is_an_error(self) -> None:
        row = event().to_row()
        del row["message"]
        with pytest.raises(KeyError, match="message"):
            row_to_sqlite("event", row)

    def test_sqlite_checks_json_booleans_and_required_columns(self) -> None:
        health = HealthRecord(**minimal_values("health"))
        good = row_to_sqlite(HealthRecord, health.to_row())
        with memory_db() as db:
            db.execute(create_table_sql(HealthRecord))
            for column, value, message in [
                ("components", "{not json", "CHECK"),
                ("flags", "nope", "CHECK"),
                ("degraded", 2, "CHECK"),
                ("state", None, "NOT NULL"),
                ("station_id", None, "NOT NULL"),
            ]:
                with pytest.raises(sqlite3.IntegrityError, match=message):
                    db.execute(insert_sql(HealthRecord), {**good, column: value})
            assert db.execute(insert_sql(HealthRecord), good).rowcount == 1


class TestKeyAndCursor:
    def test_a_duplicate_key_is_rejected(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(EventRecord))
            insert(db, event())
            with pytest.raises(sqlite3.IntegrityError, match="UNIQUE"):
                insert(db, event())
            with pytest.raises(sqlite3.IntegrityError, match="UNIQUE"):
                insert(db, event(message="Another message for the same key."))

    def test_the_station_and_the_revision_belong_to_the_key(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(EventRecord))
            ids = [
                insert(db, event()),
                insert(db, event(revision=1)),
                insert(db, event(station_id="station-b")),
                insert(db, event(t_utc_ns=1_800_000_000_000_000_001)),
            ]
        assert ids == [1, 2, 3, 4]

    def test_a_correction_is_a_new_row_after_the_cursor(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(EventRecord))
            first = insert(db, event(message="The first result."))
            cursor = first  # a sink acknowledged the first row
            insert(db, event(message="The corrected result.", revision=1))
            rows = db.execute(select_after_sql("event"), {"after": cursor, "limit": 10}).fetchall()
        assert [row["row_id"] for row in rows] == [2]
        assert rows[0]["revision"] == 1

    def test_row_ids_only_grow_and_a_deleted_id_does_not_return(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(EventRecord))
            insert(db, event(t_utc_ns=1))
            last = insert(db, event(t_utc_ns=2))
            db.execute('DELETE FROM "event" WHERE row_id = ?', (last,))
            assert insert(db, event(t_utc_ns=3)) == last + 1

    def test_a_cursor_query_pages_through_the_rows_in_order(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(EventRecord))
            for n in range(7):
                insert(db, event(t_utc_ns=100 - n))  # the times fall, the row IDs rise
            seen: list[int] = []
            cursor = 0
            while True:
                page = db.execute(
                    select_after_sql("event"), {"after": cursor, "limit": 3}
                ).fetchall()
                if not page:
                    break
                seen.extend(row["row_id"] for row in page)
                cursor = page[-1]["row_id"]
        assert seen == list(range(1, 8))

    def test_a_new_sink_starts_at_row_zero(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql(EventRecord))
            insert(db, event(t_utc_ns=1))
            rows = db.execute(select_after_sql("event"), {"after": 0, "limit": 10}).fetchall()
        assert [row["row_id"] for row in rows] == [1]


class TestUpsert:
    def test_a_repeated_record_changes_nothing(self) -> None:
        params = row_to_sqlite(EventRecord, event().to_row())
        with memory_db() as db:
            ensure_schema(db, [EventRecord])
            for _ in range(3):
                db.execute(upsert_sql(EventRecord), params)
            rows = db.execute('SELECT * FROM "event"').fetchall()
        assert len(rows) == 1
        assert rows[0]["row_id"] == 1

    def test_a_changed_record_replaces_the_row_with_the_same_key(self) -> None:
        with memory_db() as db:
            ensure_schema(db, [EventRecord])
            db.execute(upsert_sql(EventRecord), row_to_sqlite(EventRecord, event().to_row()))
            changed = event(message="A changed message.", level="warning", detail={"n": 2})
            db.execute(upsert_sql(EventRecord), row_to_sqlite(EventRecord, changed.to_row()))
            rows = db.execute('SELECT * FROM "event"').fetchall()
        assert len(rows) == 1
        stored = EventRecord.from_row(sqlite_to_row(EventRecord, rows[0]), strict=True)
        assert stored == changed

    def test_records_with_other_keys_stay_apart(self) -> None:
        with memory_db() as db:
            ensure_schema(db, [EventRecord])
            for record in [event(), event(revision=1), event(station_id="station-b")]:
                db.execute(upsert_sql(EventRecord), row_to_sqlite(EventRecord, record.to_row()))
                db.execute(upsert_sql(EventRecord), row_to_sqlite(EventRecord, record.to_row()))
            count = db.execute('SELECT count(*) FROM "event"').fetchone()[0]
        assert count == 3

    def test_the_statement_names_the_key_and_updates_everything_else(self) -> None:
        sql = upsert_sql("event")
        assert sql.startswith('INSERT INTO "event" (')
        assert 'ON CONFLICT ("station_id", "t_utc_ns", "revision") DO UPDATE SET' in sql
        assert '"message" = excluded."message"' in sql
        assert '"revision" = excluded' not in sql
        assert '"row_id"' not in sql

    @given(data=st.data())
    def test_an_upsert_is_idempotent_for_any_record(self, data: st.DataObject) -> None:
        cls = data.draw(st.sampled_from(TABLE_TYPES))
        values = data.draw(record_values(cls))
        record = cls(**values)
        params = row_to_sqlite(cls, record.to_row())
        with memory_db() as db:
            ensure_schema(db, [cls])
            db.execute(upsert_sql(cls), params)
            db.execute(upsert_sql(cls), params)
            rows = db.execute(f'SELECT * FROM "{cls.record_type}"').fetchall()
        assert len(rows) == 1
        assert cls.from_row(sqlite_to_row(cls, rows[0]), strict=True) == record


class WindowV2(SeeingWindowRecord, register=False):
    """A copy of `seeing_window` with fields that a later version adds."""

    extra_optional_arcsec: float | None = quantity(
        unit="arcsec", default=None, definition="A new optional value."
    )
    extra_flag: bool = quantity(default=True, definition="A new flag with a default.")
    extra_list: list[str] = quantity(default_factory=lambda: ["a"], definition="A new list.")
    extra_text: str = quantity(default="it's", definition="A new text with a quote.")
    extra_count: int = quantity(default=7, definition="A new count.")
    extra_blob: bytes = quantity(default=b"\x01\xff", definition="New bytes.")
    extra_float: float = quantity(default=0.5, definition="A new number.")
    extra_json: dict[str, Any] = quantity(default_factory=dict, definition="A new JSON object.")


def window_values(**overrides: Any) -> dict[str, Any]:
    values = minimal_values("seeing_window")
    values.update(overrides)
    return values


class TestMigration:
    def test_a_missing_table_is_created(self) -> None:
        assert migration_statements("event", []) == [
            create_table_sql("event"),
            *create_index_sql("event"),
        ]

    def test_a_current_table_needs_nothing(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql("event"))
            info = [tuple(row) for row in table_info(db, "event")]
        assert migration_statements("event", info) == []

    def test_new_fields_become_columns_and_old_rows_keep_working(self) -> None:
        with memory_db() as db:
            ensure_schema(db, [SeeingWindowRecord])
            old = SeeingWindowRecord(**window_values(n_frames=5))
            insert(db, old)

            info = table_info(db, "seeing_window")
            statements = migration_statements(WindowV2, info)
            assert len(statements) == 8
            assert statements[0].startswith('ALTER TABLE "seeing_window" ADD COLUMN "extra_')
            assert changed_by(db, WindowV2) == statements

            new = WindowV2(
                **window_values(t_utc_ns=2, extra_flag=False, extra_count=9, extra_text="x'y")
            )
            insert(db, new)
            old_row, new_row = db.execute(
                'SELECT * FROM "seeing_window" ORDER BY row_id'
            ).fetchall()

        migrated_old = WindowV2.from_row(sqlite_to_row(WindowV2, old_row), strict=True)
        assert migrated_old.n_frames == 5
        assert migrated_old.extra_optional_arcsec is None
        assert migrated_old.extra_flag is True
        assert migrated_old.extra_list == ["a"]
        assert migrated_old.extra_text == "it's"
        assert migrated_old.extra_count == 7
        assert migrated_old.extra_blob == b"\x01\xff"
        assert migrated_old.extra_float == 0.5
        assert migrated_old.extra_json == {}
        assert WindowV2.from_row(sqlite_to_row(WindowV2, new_row), strict=True) == new

    def test_a_migrated_table_matches_a_new_table(self) -> None:
        with memory_db() as migrated, memory_db() as fresh:
            ensure_schema(migrated, [SeeingWindowRecord])
            ensure_schema(migrated, [WindowV2])
            ensure_schema(fresh, [WindowV2])
            columns = [
                tuple(row)[1:] for row in table_info(migrated, "seeing_window")
            ]  # skip the column ID
            assert columns == [tuple(row)[1:] for row in table_info(fresh, "seeing_window")]

    def test_the_older_software_reads_a_row_that_the_newer_software_wrote(self) -> None:
        with memory_db() as db:
            ensure_schema(db, [WindowV2])
            insert(db, WindowV2(**window_values(extra_count=3)))
            row = db.execute('SELECT * FROM "seeing_window"').fetchone()
            with pytest.raises(SchemaError, match="no field"):
                ensure_schema(db, [SeeingWindowRecord])
            assert ensure_schema(db, [SeeingWindowRecord], allow_extra_columns=True) == []
        record = SeeingWindowRecord.from_row(sqlite_to_row(SeeingWindowRecord, row), strict=True)
        assert record == SeeingWindowRecord(**window_values())

    def test_a_second_call_changes_nothing(self) -> None:
        with memory_db() as db:
            assert ensure_schema(db, [SeeingWindowRecord])
            assert ensure_schema(db, [SeeingWindowRecord]) == []
            assert len(ensure_schema(db, [WindowV2])) == 8
            assert ensure_schema(db, [WindowV2]) == []

    def test_a_required_new_field_without_a_default_is_an_error(self) -> None:
        class NeedsValue(SeeingWindowRecord, register=False):
            needed: int = quantity(definition="A required value.")

        with memory_db() as db:
            ensure_schema(db, [SeeingWindowRecord])
            with pytest.raises(SchemaError, match="new field needed must be optional"):
                ensure_schema(db, [NeedsValue])

    def test_a_retyped_field_is_an_error(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql("event").replace('"message" TEXT', '"message" INTEGER'))
            with pytest.raises(SchemaError, match=r"column message is INTEGER.*retyped"):
                ensure_schema(db, [EventRecord])

    def test_an_optional_field_that_became_required_in_the_table_is_an_error(self) -> None:
        with memory_db() as db:
            db.execute(create_table_sql("event").replace('"detail" TEXT', '"detail" TEXT NOT NULL'))
            with pytest.raises(SchemaError, match="column detail is NOT NULL"):
                ensure_schema(db, [EventRecord])

    def test_a_required_field_in_a_nullable_column_is_harmless(self) -> None:
        with memory_db() as db:
            db.execute(
                create_table_sql("event").replace('"message" TEXT NOT NULL', '"message" TEXT')
            )
            assert ensure_schema(db, [EventRecord]) == []

    def test_a_table_without_a_row_id_is_an_error(self) -> None:
        info = [(0, "station_id", "TEXT", 1, None, 0)]
        with pytest.raises(SchemaError, match="row_id"):
            migration_statements("event", info)

    def test_every_problem_is_reported_at_once(self) -> None:
        info = [
            (0, "row_id", "INTEGER", 0, None, 1),
            (1, "message", "BLOB", 1, None, 0),
            (2, "removed_field", "TEXT", 0, None, 0),
        ]
        with pytest.raises(SchemaError) as error:
            migration_statements("event", info)
        message = str(error.value)
        assert "column message is BLOB" in message
        assert "removed_field has no field" in message

    def test_the_plan_reads_the_rows_of_a_pragma_as_tuples_or_rows(self) -> None:
        with memory_db() as db:
            ensure_schema(db, [SeeingWindowRecord])
            rows = table_info(db, "seeing_window")
        as_tuples = [tuple(row) for row in rows]
        assert migration_statements(WindowV2, rows) == migration_statements(WindowV2, as_tuples)


def changed_by(db: sqlite3.Connection, record: type[Record]) -> list[str]:
    return ensure_schema(db, [record])
