"""The Markdown quantity reference, generated from the record declarations.

`render_reference` returns the text of `docs/quantities.md`. Regenerate the file after you
change a declaration:

    seeingmon records reference --output docs/quantities.md

A test fails when the committed file differs from the generated text.
"""

from __future__ import annotations

from collections.abc import Iterable

from seeingmon.records.base import (
    KEY_FIELDS,
    RECORD_TYPES,
    FieldSpec,
    Record,
    base_field_specs,
    doc_paragraphs,
    field_specs,
    resolve_record_type,
)

COMMAND = "seeingmon records reference"
OUTPUT_PATH = "docs/quantities.md"

NOTE = (
    f"> This file is generated by `{COMMAND}` from the record declarations in\n"
    "> `src/seeingmon/records/`. Do not edit it by hand. To change a definition, edit the\n"
    f"> declaration and run `{COMMAND} --output {OUTPUT_PATH}`."
)

INTRODUCTION = """\
This reference lists every field of every record type that the system stores and serves. The \
system declares each record type once, and the SQLite schema, the sink mappings, the API schema, \
and this reference all come from that declaration.

## Conventions

- **Key.** A record is identified by its record type and `({key})`. A sink upserts by this key, \
so sending a record twice changes nothing. A correction is a new record with the next \
`revision`.
- **Names carry units.** The name of a field ends with its unit, such as `seeing_fwhm_arcsec` \
or `exposure_us`. The unit column repeats it.
- **Missing values.** A missing value is `null`, and the `quality` field says why. A field that \
is optional can be `null`, and a required field never is.
- **Time.** `t_utc_ns` is a number of nanoseconds since the Unix epoch, in UTC. The API can \
add an ISO 8601 time next to it.
- **Types.** A `bytes` value is base64 text in a row and a BLOB in SQLite. A `list` or a `dict` \
is a JSON array or object in a row and JSON text in SQLite.
- **Storage.** A `table` record is a row of a SQLite table, and its `row_id` is the sink \
cursor. A `segment` record is a row of a binary segment file.
- **Changes.** A new field goes at the end of its record, and it is optional or has a default. \
The rules are in the documentation of `src/seeingmon/records/base.py`.\
"""


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _row(spec: FieldSpec, *, segment: bool) -> str:
    type_text = f"`{spec.type_name}`"
    if segment and spec.dtype is not None:
        type_text += f" (`{spec.dtype}`)"
    unit = f"`{spec.unit}`" if spec.unit is not None else "none"
    optional = "Yes" if spec.nullable else "No"
    cells = [f"`{spec.name}`", type_text, unit, _cell(spec.definition), optional]
    return "| " + " | ".join(cells) + " |"


def _fields_table(specs: Iterable[FieldSpec], *, segment: bool) -> list[str]:
    lines = ["| Field | Type | Unit | Definition | Optional |", "|---|---|---|---|---|"]
    lines.extend(_row(spec, segment=segment) for spec in specs)
    return lines


def _codes_tables(specs: Iterable[FieldSpec]) -> list[str]:
    lines: list[str] = []
    for spec in specs:
        if spec.codes is None:
            continue
        lines += ["", f"Codes for `{spec.name}`:", "", "| Code | Meaning |", "|---|---|"]
        lines.extend(f"| `{code}` | {_cell(meaning)} |" for code, meaning in spec.codes.items())
    return lines


def _retention(cls: type[Record]) -> str:
    if cls.retention_days is None:
        return "kept forever"
    unit = "day" if cls.retention_days == 1 else "days"
    return f"{cls.retention_days} {unit}"


def _record_section(cls: type[Record]) -> list[str]:
    specs = [spec for spec in field_specs(cls) if not spec.base]
    segment = cls.storage == "segment"
    lines = [f"## `{cls.record_type}`", ""]
    for paragraph in doc_paragraphs(cls):
        lines += [paragraph, ""]
    where = "a row of a segment file" if segment else "a row of a SQLite table"
    lines += [f"Storage: {where}. Retention: {_retention(cls)}.", ""]
    if segment:
        time = next(spec for spec in base_field_specs() if spec.name == "t_utc_ns")
        lines += [
            "The type in parentheses is the storage type of the field in a row. A row also "
            f"stores `{time.name}` as `{time.dtype}`.",
            "",
        ]
    lines += _fields_table(specs, segment=segment)
    lines += _codes_tables(specs)
    return lines


def render_reference() -> str:
    """The text of the quantity reference. It ends with a newline."""
    base = base_field_specs()
    lines = [NOTE, "", "# Quantity reference", ""]
    lines += [INTRODUCTION.format(key=", ".join(KEY_FIELDS)), ""]
    lines += ["## Fields of every record", ""]
    lines += ["Every record has these fields, and the tables below do not repeat them.", ""]
    lines += _fields_table(base, segment=False)
    for name in RECORD_TYPES:
        lines += ["", *_record_section(resolve_record_type(name))]
    return "\n".join(lines) + "\n"
